<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Install JDPC CMS</title><style>
:root{font-family:system-ui,sans-serif;color:#17201a;background:#f0f5f1}*{box-sizing:border-box}body{margin:0;padding:32px 16px}.card{max-width:880px;margin:auto;background:#fff;border-radius:14px;box-shadow:0 12px 40px #15351e20;overflow:hidden}.head{padding:28px 32px;background:#087b36;color:#fff}.head h1{margin:0 0 6px}.body{padding:28px 32px}fieldset{border:1px solid #d8e2da;border-radius:8px;margin:0 0 24px;padding:20px}legend{font-weight:700;padding:0 8px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.full{grid-column:1/-1}label{display:block;font-size:14px;font-weight:600;margin-bottom:5px}input{width:100%;padding:11px;border:1px solid #b8c6bb;border-radius:6px;font:inherit}.requirements{list-style:none;padding:0}.requirements li{padding:5px}.ok{color:#087b36}.bad{color:#b42318}.alert{padding:12px;border-radius:6px;background:#fff1f1;color:#9b1c1c;margin-bottom:16px}.help{padding:12px;background:#fff8dd;border:1px solid #ead990;border-radius:6px}.submit{background:#087b36;color:#fff;border:0;border-radius:7px;padding:13px 24px;font-weight:700;cursor:pointer}@media(max-width:650px){.grid{grid-template-columns:1fr}.body,.head{padding:22px}}
</style></head><body><div class="card"><div class="head"><h1>JDPC CMS installer</h1><div>Secure, one-time cPanel setup</div></div><div class="body">
@if($errors->any())<div class="alert"><strong>Installation needs attention.</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
@if(!$keyAvailable)<div class="help"><strong>Installation key is missing.</strong> Upload the complete production package again. It must include <code>storage/app/install.key</code>. The matching key is shown in <code>INSTALL-KEY.txt</code>.</div>@endif
<h2>Server requirements</h2><ul class="requirements">@foreach($requirements as $label=>$met)<li class="{{ $met?'ok':'bad' }}">{{ $met?'✓':'✕' }} {{ $label }}</li>@endforeach</ul>
<form method="post" action="{{ route('install.run') }}" autocomplete="off">@csrf
<fieldset><legend>Installation authorization</legend><label for="installer_key">Installation key</label><input id="installer_key" type="password" name="installer_key" required placeholder="Copy from INSTALL-KEY.txt"></fieldset>
<fieldset><legend>Site</legend><label for="app_url">Public site URL</label><input id="app_url" type="url" name="app_url" value="{{ old('app_url', request()->getSchemeAndHttpHost()) }}" required></fieldset>
<fieldset><legend>MySQL database</legend><div class="grid"><div><label for="db_host">Host</label><input id="db_host" name="db_host" value="{{ old('db_host','localhost') }}" required></div><div><label for="db_port">Port</label><input id="db_port" name="db_port" type="number" value="{{ old('db_port','3306') }}" required></div><div><label for="db_database">Database</label><input id="db_database" name="db_database" value="{{ old('db_database') }}" required></div><div><label for="db_username">Username</label><input id="db_username" name="db_username" value="{{ old('db_username') }}" required></div><div class="full"><label for="db_password">Password</label><input id="db_password" type="password" name="db_password"></div></div></fieldset>
<fieldset><legend>First administrator</legend><div class="grid"><div><label for="admin_name">Name</label><input id="admin_name" name="admin_name" value="{{ old('admin_name') }}" required></div><div><label for="admin_email">Email</label><input id="admin_email" type="email" name="admin_email" value="{{ old('admin_email') }}" required></div><div><label for="admin_password">Password</label><input id="admin_password" type="password" name="admin_password" minlength="12" required></div><div><label for="admin_password_confirmation">Confirm password</label><input id="admin_password_confirmation" type="password" name="admin_password_confirmation" minlength="12" required></div></div><p>Use at least 12 characters with upper-case, lower-case, and numeric characters.</p></fieldset>
<button class="submit" type="submit" @disabled(!$keyAvailable || in_array(false,$requirements,true))>Install site and import content</button>
</form></div></div></body></html>
