<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;use App\Models\AuditLog;use App\Models\Setting;use App\Rules\SafeUrl;use App\Support\HtmlSanitizer;use Illuminate\Http\Request;use Illuminate\Support\Facades\Validator;use Illuminate\Validation\Rule;use Illuminate\Validation\ValidationException;use JsonException;
class SettingController extends Controller
{
 public function index(){$settings=Setting::orderBy('group')->orderBy('key')->get()->groupBy('group');return view('admin.settings.index',compact('settings'));}
 public function store(Request $r,HtmlSanitizer $s){$d=$r->validate(['key'=>'required|regex:/^[a-z0-9_.-]+$/|max:128|unique:settings,key','group'=>'required|max:64','type'=>['required',Rule::in(['string','text','html','url','boolean','json'])],'value_bn'=>'nullable|max:1000000','value_en'=>'nullable|max:1000000','is_public'=>'nullable|boolean']);$d=$this->clean($d,$s);$setting=Setting::create($d);$this->audit($r,$setting,'setting.created');return back()->with('status','সেটিং তৈরি হয়েছে।');}
 public function update(Request $r,Setting $setting,HtmlSanitizer $s){$d=$r->validate(['value_bn'=>'nullable|max:1000000','value_en'=>'nullable|max:1000000','type'=>['required',Rule::in(['string','text','html','url','boolean','json'])],'is_public'=>'nullable|boolean']);$old=$setting->getOriginal();$setting->update($this->clean($d,$s));$this->audit($r,$setting,'setting.updated',$old);return back()->with('status','সেটিং হালনাগাদ হয়েছে।');}
 public function destroy(Request $r,Setting $setting){$old=$setting->getOriginal();$setting->delete();$this->audit($r,$setting,'setting.deleted',$old);return back()->with('status','সেটিং মুছে ফেলা হয়েছে।');}
 private function clean(array $d,HtmlSanitizer $s):array{if(($d['type']??'')==='url')Validator::make($d,['value_bn'=>['nullable',new SafeUrl],'value_en'=>['nullable',new SafeUrl]])->validate();if(($d['type']??'')==='json'){foreach(['value_bn','value_en'] as $f)if(filled($d[$f]??null)){try{json_decode($d[$f],true,512,JSON_THROW_ON_ERROR);}catch(JsonException){throw ValidationException::withMessages([$f=>'সঠিক JSON লিখুন।']);}}}if(($d['type']??'')==='html'){foreach(['value_bn','value_en'] as $f)$d[$f]=$s->clean($d[$f]??'');}$d['is_public']=request()->boolean('is_public');return $d;}
 private function audit(Request $r,Setting $s,string $event,?array $old=null):void{AuditLog::create(['user_id'=>$r->user()->id,'event'=>$event,'auditable_type'=>$s->getMorphClass(),'auditable_id'=>$s->id,'old_values'=>$old,'new_values'=>$s->getAttributes(),'ip_address'=>$r->ip(),'user_agent'=>$r->userAgent()]);}
}
